dist: xenial
language: scala

scala:
  - 2.13.1
  - 2.12.10

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile;
  - find $HOME/.sbt -name "*.lock" | xargs rm
